import { Todo } from '../models/todo.model';

export const MOCK_TODOS: Todo[] = [
  {
    id: '1',
    assignedToUserId: '1',
    assignedByUserId: '1',
    title: 'Practice NgRx actions',
    description: 'Create login, logout and todo loading actions.',
    completed: true,
    priority: 'medium',
    createdAt: '2026-06-19',
    deadline: '2026-06-21',
  },
  {
    id: '2',
    assignedToUserId: '1',
    assignedByUserId: '2',
    title: 'Build the todo list UI',
    description: 'Create a Gmail-like todo list layout with sender id, title and description.',
    completed: false,
    priority: 'high',
    createdAt: '2026-06-20',
    deadline: '2026-06-24',
  },
  {
    id: '3',
    assignedToUserId: '1',
    assignedByUserId: '3',
    title: 'Connect todos to the logged-in user',
    description: 'Only show todos where assignedToUserId matches the current user id.',
    completed: false,
    priority: 'high',
    createdAt: '2026-06-20',
    deadline: null,
  },
  {
    id: '4',
    assignedToUserId: '1',
    assignedByUserId: '2',
    title: 'Prepare register page',
    description: 'Use the login page and auth NgRx flow as a pattern for registration.',
    completed: false,
    priority: 'medium',
    createdAt: '2026-06-21',
    deadline: '2026-06-26',
  },
  {
    id: '5',
    assignedToUserId: '2',
    assignedByUserId: '1',
    title: 'Review Angular routing',
    description: 'Check protected routes, redirect behavior and the auth guard.',
    completed: false,
    priority: 'medium',
    createdAt: '2026-06-18',
    deadline: '2026-06-25',
  },
  {
    id: '6',
    assignedToUserId: '2',
    assignedByUserId: '3',
    title: 'Test logout behavior',
    description: 'Make sure logout clears the auth state and redirects to the login page.',
    completed: true,
    priority: 'low',
    createdAt: '2026-06-17',
    deadline: '2026-06-20',
  },
  {
    id: '7',
    assignedToUserId: '3',
    assignedByUserId: '1',
    title: 'Create mock todo API',
    description: 'Move todo loading behind a TodoApi abstraction for mock and real backend switching.',
    completed: false,
    priority: 'high',
    createdAt: '2026-06-22',
    deadline: '2026-06-27',
  },
  {
    id: '8',
    assignedToUserId: '3',
    assignedByUserId: '2',
    title: 'Clean up mock data',
    description: 'Move users and todos into separate mock-data files.',
    completed: true,
    priority: 'low',
    createdAt: '2026-06-16',
    deadline: null,
  },
];