import { Todo } from '../models/todo.model';

export const MOCK_TODOS: Todo[] = [
  {
    id: '1',
    ownerId: '1',
    title: 'Practice NgRx actions',
    description: 'Create and dispatch login actions.',
    completed: true,
    priority: 'medium',
    createdAt: '2026-06-19',
    deadline: '2026-06-21',
  },
  {
    id: '2',
    ownerId: '1',
    title: 'Build login flow',
    description: 'Connect LoginPage with AuthEffects and MockAuthApi.',
    completed: false,
    priority: 'high',
    createdAt: '2026-06-19',
    deadline: '2026-06-22',
  },
  {
    id: '3',
    ownerId: '1',
    title: 'Create todo feature state',
    description: 'Add todo actions, reducer, selectors and effects.',
    completed: false,
    priority: 'high',
    createdAt: '2026-06-19',
    deadline: null,
  },
  {
    id: '4',
    ownerId: '2',
    title: 'Review Angular routing',
    description: 'Check protected routes and route guards.',
    completed: false,
    priority: 'medium',
    createdAt: '2026-06-18',
    deadline: '2026-06-25',
  },
  {
    id: '5',
    ownerId: '2',
    title: 'Prepare registration page',
    description: 'Use the login flow as a pattern.',
    completed: false,
    priority: 'low',
    createdAt: '2026-06-18',
    deadline: null,
  },
  {
    id: '6',
    ownerId: '3',
    title: 'Test logout behavior',
    description: 'Make sure the header changes after logout.',
    completed: true,
    priority: 'low',
    createdAt: '2026-06-17',
    deadline: '2026-06-20',
  },
];